# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title sources
#'
#' @description Get a list of source nodes from a network.
#'
#' @details Extract a list of source nodes, i.e. nodes that do not have any
#' inputs, from a network.
#'
#' @param edge_list A dataframe containing a list of edges (see \code{\link{popsnetwork}}
#' for a description of possible formats).
#'
#' @return A list of ids of all source nodes in the network.
sources <- function(edge_list) {
    .Call('rpathsonpaths_sources', PACKAGE = 'rpathsonpaths', edge_list)
}

#' @title colour_network
#'
#' @description Identify separate sub-networks.
#'
#' @details This function identifies completely separate sub-networks in a network
#' described as an edge list.
#'
#' @param edge_list A dataframe containing a list of edges (see \code{\link{popsnetwork}}
#' for a description of possible formats).
#'
#' @return An integer vector with the sub-network id of each edge. Note that id's start at
#' 1 and are not guaranteed to be contiguous.
colour_network <- function(edge_list) {
    .Call('rpathsonpaths_colour_network', PACKAGE = 'rpathsonpaths', edge_list)
}

#' @title cycles
#' 
#' @description Detect cycles in a network.
#' 
#' @details This function detects circular connections in a network.
#'
#' @param edge_list A dataframe containing a list of edges (see \code{\link{popsnetwork}}
#' for a description of possible formats).
#' @param record Whether to return a list of cycles.
#' 
#' @return If record is FALSE: TRUE if a cycle was found, FALSE otherwise. If record is TRUE:
#' a list of cycles (as vectors of node ids, see \code{\link{popsnetwork}}) is returned.
cycles <- function(edge_list, record = FALSE) {
    .Call('rpathsonpaths_cycles', PACKAGE = 'rpathsonpaths', edge_list, record)
}

#' @title popsnetwork 
#'
#' @description Create a popsnetwork object.
#'
#' @details A popsnetwork object stores the nodes and edges making up a food transport
#' network and associated data describing spread of infected diseases on the
#' network. A network is created from a tabular description of its edges.
#'
#' @section Edge lists and node ids:
#' Many functions in rpathsonpaths take edge lists as an argument. An edge list is a 
#' data frame with at least two columns. These columns can be either integer vectors
#' which will be interpreted as \emph{0-based node indices} or factors. In general where
#' applicable functions will return the same format they received. Note that formats 
#' can not be mixed easily. Function arguments (and data frame columns) have to have the 
#' same type. Furthermore nodes in a \code{popsnetwork} object generated with integer
#' indices can not be referenced by name.
#'
#' In general integer indices are considerably faster than factors.
#'
#' @param links A dataframe describing all edges in the graph as well as transfer rates
#' between them. The first two columns are read as inputs and outputs. If there are only 
#' two columns all rates are assumed to be 1.
#' @param external A dataframe describing external inputs into the network as $nodes
#' and $rates.
#' @param transmission Rate of infection within nodes.
#' @param checks Perform some basic integrity checks on input data (currently looks for cycles
#' and disconnected sub-networks).
#' @return A popsnetwork object.
popsnetwork <- function(links, external, transmission = 0.0, checks = FALSE) {
    .Call('rpathsonpaths_popsnetwork', PACKAGE = 'rpathsonpaths', links, external, transmission, checks)
}

.printpopsnetwork <- function(p_net) {
    invisible(.Call('rpathsonpaths_print_popsnetwork', PACKAGE = 'rpathsonpaths', p_net))
}

.printpopsnode <- function(p_node) {
    invisible(.Call('rpathsonpaths_print_popsnode', PACKAGE = 'rpathsonpaths', p_node))
}

#' @title set_allele_freqs
#' 
#' @description Pre-set allele frequencies for some nodes.
#' 
#' @details Use this function to initialize allele frequencies for some nodes of the network.
#' 
#' @param p_net A popsnetwork object.
#' @param ini_dist Initial distribution of allele frequencies. ini_dist has to be 
#' a list
#' containing a vector of node IDs (see \code{\link{popsnetwork}}) and
#' a matrix of allele frequencies. Note that *any* node pre-set in this
#' way will be treated as a source only by \code{spread_dirichlet}.
#' @return A new popsnetwork object.
set_allele_freqs <- function(p_net, ini_dist) {
    .Call('rpathsonpaths_set_allele_freqs', PACKAGE = 'rpathsonpaths', p_net, ini_dist)
}

#' @title spread_dirichlet
#' 
#' @description Simulate spread of pathogens on the network using a Dirichlet
#' distribution to approximate genetic drift.
#' 
#' @details This function simulates the change of gene frequencies in a population
#' of pathogens as they spread through the transport network starting at the 
#' external sources (see \code{\link{popsnetwork}}). At each node founder
#' effects are assumed to change composition of the population. This change is 
#' approximated by drawing a set of allele frequencies from a Dirichlet distribution.
#' 
#' @param p_net A popsnetwork object.
#' @param theta Scale parameter of the Dirichlet distribution. At each node the Dirichlet
#' distribution the new allele frequencies ar drawn from is parameterized by the old
#' frequencies multiplied by theta.
#' @param ini_dist Initial distribution of allele frequencies (optional). ini_dist has to be 
#' a list
#' containing a vector of node IDs (see \code{\link{popsnetwork}}) and
#' a matrix of allele frequencies. Note that *any* node pre-set in this
#' way will be treated as a source only.
#' @return A new popsnetwork object with allele frequencies set for each node.
spread_dirichlet <- function(p_net, theta, ini_dist = NULL) {
    .Call('rpathsonpaths_spread_dirichlet', PACKAGE = 'rpathsonpaths', p_net, theta, ini_dist)
}

#' @title get_popsnode
#'
#' @description Pick a single node from the network.
#' 
#' @param p_net A PopsNet object.
#' @param id The id of the node to return (either a string or an integer, see 
#' \code{\link{popsnetwork}}).
#' @return A popsnode object.
get_popsnode <- function(p_net, id) {
    .Call('rpathsonpaths_get_popsnode', PACKAGE = 'rpathsonpaths', p_net, id)
}

#' @title draw_isolates.popsnode
#'
#' @description Draw a set of isolates from a single node.
#'
#' @details Draw a random set of isolates from a given node. This will only work if
#' allele frequencies have been set (manually or by simulation).
#'
#' @param p_node A popsnode object.
#' @param n Number of isolates to draw.
#' @return A vector of allele counts.
draw_isolates.popsnode <- function(p_node, n) {
    .Call('rpathsonpaths_draw_isolates_popsnode', PACKAGE = 'rpathsonpaths', p_node, n)
}

#' @title draw_isolates.popsnetwork
#'
#' @description Draw a set of isolates from the network.
#' 
#' @details Draw a random set of isolates from a number of nodes in the network. This will
#' *only* work if allele frequencies have been set or simulated.
#'
#' @param p_net a PopsNet object.
#' @param samples Number of samples to draw from each node. This has to be a dataframe
#' with node ids (see \code{\link{popsnetwork}}) in the first and number of isolates to 
#' draw in the second column.
#' @return A dataframe containing node id in $node and number of isolates with allele \code{x}
#' in $\code{allele_x}.
draw_isolates.popsnetwork <- function(p_net, samples) {
    .Call('rpathsonpaths_draw_isolates_popsnetwork', PACKAGE = 'rpathsonpaths', p_net, samples)
}

#' @title egdeList
#'
#' @description Get a list of edges in a dataframe.
#'
#' @description This function returns a list of the edges in the network in a format
#' that is suitable for plotting with e.g. iGraph.
#'
#' @param p_net A PopsNet object.
#' @return A dataframe with from, to, rates and rates_infected.
edge_list <- function(p_net) {
    .Call('rpathsonpaths_edge_list', PACKAGE = 'rpathsonpaths', p_net)
}

#' @title node_list
#'
#' @description Get a list of nodes in a dataframe.
#'
#' @description This function returns a list of the nodes in the network in a format
#' that is suitable for plotting with e.g. iGraph.
#'
#' @param p_net A PopsNet object.
#' @return A dataframe with id and rate_infected.
node_list <- function(p_net) {
    .Call('rpathsonpaths_node_list', PACKAGE = 'rpathsonpaths', p_net)
}

